### PR TITLE
Message tweaks

### PR DESCRIPTION
**Pull request by sfrooster**

### CODE REVIEW

**Comment by kcarlson2915** [comment]
as far as I can tell, there is no reason not to have the messages have all private fields with public getters and setters, I can make those changes.

**Comment by kcarlson2915** [comment]
Also, is there a reason this repo isn't private and the others are? Do we want to close this one?

**Comment by sfrooster** [comment]
It works just fine with private vars and public setters and that feels like
the better way.

**Comment by sfrooster** [comment]
Nope.

**Pull request merged**
